### ISSUE TITLE
Clone checkout Failed (Inflater) 

### ISSUE THREAD

**Issue by Zacharia2** [Zacharia2/MGit#15]
目前jgit已修复这个问题 好像是流式。问题主要定位于clone相关模块。是因为Java堆内存不足导致的。主要发生于较大仓库的克隆上。目前只和git中存储的单个文件大小有关系，单个文件大小不能超过一定数量，目前推荐是50MB。

目前两种修复方式，调整jgit的config尝试适配Android环境。

在代码层面对某几个方法流程进行修补。

到checkout 就失败了

```java
set exception
java.lang.NullPointerException: Inflater has been closed
at java.util.zip.Inflater.ensureOpen(Inflater.java:730)
at java.util.zip.Inflater.reset(Inflater.java:697)
at org.eclipse.jgit.lib.InflaterCache.release(InflaterCache.java:61)
at org.eclipse.jgit.internal.storage.file.WindowCursor.close(WindowCursor.java:341)
at org.eclipse.jgit.internal.storage.file.PackInputStream.close(PackInputStream.java:50)
at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:292)
at java.io.BufferedInputStream.close(BufferedInputStream.java:476)
at org.eclipse.jgit.lib.ObjectStream$Filter.close(ObjectStream.java:206)
at org.eclipse.jgit.dircache.DirCacheCheckout.getContent(DirCacheCheckout.java:1635)
at org.eclipse.jgit.dircache.DirCacheCheckout.getContent(DirCacheCheckout.java:1558)
at org.eclipse.jgit.dircache.Checkout.checkout(Checkout.java:195)
at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:577)
at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:480)
at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:393)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:214)
at xyz.realms.mgit.tasks.repo.CloneTask.cloneRepo(CloneTask.java:99)
at xyz.realms.mgit.tasks.repo.CloneTask.doInBackground(CloneTask.java:45)
at xyz.realms.mgit.tasks.repo.CloneTask.doInBackground(CloneTask.java:29)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:290)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
2025-01-12 19:41:39.358  7306-7898  CloneTask               xyz.realms.mgit                      E  del repo. clone failed
```

就是这个文件：Other/pdf参考资料/高等数学 第7版 上册 同济大学.pdf，比较大导致出问题了。

在完成某些操作后，资源（如 Inflater）没有被正确地关闭或重置，导致后续操作尝试使用已经关闭的资源。

Inflater 没有被正确地重置

```java
	public static void release(Inflater i) {
		if (i != null) {
			i.reset();  执行这个的时候直接没了失败了应该是。
			if (releaseImpl(i))
				i.end();
		}
	}
```

检出到73.3MB/75.1MB就i.reset(); 失败了。

java. util. zip. Inflater public void reset() : Resets inflater so that a new set of input data can be processed.

```java
    private final InflaterZStreamRef zsRef;
    private void ensureOpen () {
        assert Thread.holdsLock(zsRef);
        if (zsRef.address() == 0)
            throw new NullPointerException("Inflater has been closed");
    }
```

修改jgit配置失败。修改配置似乎不能解决问题。此问题似乎是内存不够所致。

```java
ObjectStream
public int read(byte[] b, int off, int len) throws IOException {
			return in.read(b, off, len); //在这里还没有完全写出就失败了。
		}
```

```java
DirCacheCheckout

        } else {
            try (InputStream in = inputStream.load()) {
                in.transferTo(channel); // caller getContent outstream, tmpFile in /storage/emulated/0/Android/data/xyz.realms.mgit/files/repo
            }
        }

LargePackedWholeObject
            in = new BufferedInputStream( //
            new InflaterInputStream( //
                in, //
                wc.inflater(), //
                8192), //
            8192);
        return new ObjectStream.Filter(type, size, in);

ObjectStream
        public int read(byte[] b, int off, int len) throws IOException {
            return in.read(b, off, len);
        }
```

**Comment by Zacharia2** [comment]
https://gist.github.com/matthewmccullough/2695758


这篇文章主要讲述了Git在处理对象存储时的压缩和差异（deltas）机制。具体来说，文章通过以下步骤来解释Git的这一特性：


• Git对象压缩：文章指出，在提交时，Git不会立即对对象（如文件）进行差异压缩，而是等到打包文件（packfile）创建时才进行。


• 示例演示：作者通过创建一个Git仓库，并在其中添加一个未压缩的TIFF图像文件，然后对该图像进行微小修改并再次提交，来展示Git如何处理文件的压缩。


• 压缩效果：文章展示了在提交时，尽管文件被压缩存储，但差异压缩的效果直到执行`git gc --aggressive`命令，将松散对象打包成单一的打包文件时才显现出来，从而显著减少了存储空间。


• 用户反馈：文章下方的评论部分提供了对文章内容的反馈，包括对Git压缩机制的赞扬和对`du`命令使用的建议，以更准确地报告磁盘使用情况。


• 核心观点：文章的核心观点是，Git在打包文件级别上通过差异压缩来优化存储空间，而不是在单个提交时。这有助于减少仓库的存储需求，尤其是在处理大型文件时。

**Comment by Zacharia2** [comment]
https://github.com/rtyley/agit/blob/master/agit/src/main/java/com/madgag/android/jgit/HarmonyFixInflater.java

**Comment by Zacharia2** [comment]
AndroidManifest.xml  中设置  android:largeHeap="true"  来申请更多的堆内存，例如将内存限制提高到512M[^1^]。

**Comment by Zacharia2** [comment]
android:largeHeap="true"已写

**Comment by Zacharia2** [comment]
https://github.com/rtyley/agit/blob/master/agit%2Fsrc%2Fmain%2Fjava%2Fcom%2Fmadgag%2Fagit%2FDashboardActivity.java

https://github.com/rtyley/agit/blob/master/agit%2Fsrc%2Fmain%2Fjava%2Fcom%2Fmadgag%2Fagit%2Foperations%2FGitOperationExecutor.java

**Comment by Zacharia2** [comment]
https://github.com/Zacharia2/MGit/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fxinglan%2Fmgit%2Ftransport%2FMGitHttpConnectionFactory.java#L62-L67

https://github.com/eclipse-egit/egit/blob/master/org.eclipse.egit.core%2Fsrc%2Forg%2Feclipse%2Fegit%2Fcore%2Fop%2FCloneOperation.java

**Comment by Zacharia2** [comment]
https://eclipse.gerrithub.io/q/project:eclipse-jgit/jgit,50

**Comment by Zacharia2** [comment]
https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/25449

https://bugs.eclipse.org/bugs/show_bug.cgi?id=394078

旧版本已修复，新版本已包含，可能和这个问题无关。

**Comment by Zacharia2** [comment]
以下是对`packedGitLimit`、`streamFileThreshold`、`packedGitOpenFiles`和`deltaBaseCacheLimit`这些Git选项的含义解释：


• packedGitLimit：

• 这个选项定义了Git包文件存储在内存中的最大缓存大小。它决定了JGit可以预留多少内存用来缓存包文件的数据，以提高访问效率。


• streamFileThreshold：

• `streamFileThreshold`为必须流式传输的对象设置新的字节限制。如果对象大小超过这个阈值，它将被流式传输，而不是完全加载到内存中。这有助于避免内存溢出，特别是在处理大文件时。


• packedGitOpenFiles：

• 这个配置项指定了一次可以打开的最大包文件数。这是一个性能相关的设置，可以影响Git操作时能同时访问多少个包文件。


• deltaBaseCacheLimit：

• `deltaBaseCacheLimit`定义了用于存储 deltified 对象基底的缓存大小限制。这个设置可以减少读取 deltified 对象时所需的磁盘I/O操作，通过缓存基底对象来加速访问。

这些选项主要用于调整Git（特别是JGit）在处理大量数据时的性能和资源使用情况，通过合理配置这些参数，可以优化大型项目或服务器上Git操作的性能。

**Comment by Zacharia2** [comment]
`core.bigFileThreshold`是 Git 配置中的一个参数，它的作用是指定文件大小的阈值，超过这个阈值的文件将不会被尝试进行增量压缩（delta compression）。这意味着，对于大于这个阈值的文件，Git 将存储整个文件内容，而不是仅存储文件之间的差异，从而避免过度使用内存。所有平台上的默认值通常是512 MiB。

设置`core.bigFileThreshold`可以优化 Git 在处理大文件时的性能和资源使用。例如，对于大型的二进制文件，增量压缩可能没有效果，因此可以设置一个较高的`core.bigFileThreshold`值，使得这些大文件不经过增量压缩直接存储，这样可以减少内存的使用，但可能会略微增加磁盘的使用率。

要设置`core.bigFileThreshold`，可以使用以下命令：





其中`<size>`是你想要设置的阈值大小，可以包含单位，如`1g`表示1GB，`512m`表示512MB。设置后，任何超过这个大小的文件都将以完整形式存储，而不是作为delta（差异）存储，这有助于减少处理大文件时的内存消耗。

**Comment by Zacharia2** [comment]
https://github.com/sheimi/SGit/issues/65#issuecomment-73890069


这个GitHub issue讨论的核心问题是关于sGit应用在克隆仓库时遇到的“Inflater after calling end”错误，以及与克隆大仓库相关的问题。以下是关键点的总结：


• 错误描述：多个用户报告在使用sGit克隆仓库时遇到错误，表现为“attempt to use Inflater after calling end”。这个错误涉及到Java的zip库Inflater的使用问题。


• 问题复现：用户benjaminoakes和bugabinga等均报告了类似的问题，无论是通过HTTPS还是SSH方式克隆，都会出现应用崩溃或无法完成克隆的情况。


• ART和Dalvik问题：有用户指出，这个问题与Android的运行时环境有关，特别是在使用ART时更为明显。ART是Android Runtime的简称，是Dalvik的替代品。


• 仓库大小问题：bluebirch提到在克隆一个特别大的仓库（约400MB）时出现了这个错误，暗示这可能与仓库的大小有关。


• 解决方案和建议：

• 对于大仓库的管理，Atlassian建议使用`git gc`来优化存储，并调整`.gitattributes`中的delta压缩设置。

• 使用Git的稀疏检出（sparse checkout）功能，允许只检出工作目录中需要的特定文件夹。

• 使用Git LFS来处理大文件，避免大文件直接存储在Git仓库中，从而减少克隆仓库的时间。

• 对于克隆大仓库的问题，建议使用浅克隆（shallow clones）来减少初次克隆的数据量。


• 其他相关讨论：MrDanielSan提到这个问题可能是jgit在Android上的一个已知问题，并提供了一个可能的解决方案，即采用一个修补过的jgit版本。

综上所述，这个问题涉及到sGit应用在处理大仓库克隆时的内存和性能限制，以及与Android运行时环境的兼容性问题。用户可以尝试上述建议的解决方案来改善克隆大仓库时遇到的问题。



处理大仓库的内存问题：
 对于克隆大仓库时遇到的内存问题，可以通过限制JGit打开的包文件数量和窗口大小来优化内存使用。例如，设置  core.packedGitLimit  和  core.packedGitWindowSize  来控制内存中的包文件缓存大小[^3^]。


使用浅克隆（Shallow Clone）：
 为了减少从服务器下载的数据量，可以创建浅克隆。这可以通过设置  --depth 1  参数来实现，只下载最新的提交，从而减少内存和带宽的使用[^0^]。

**Comment by Zacharia2** [comment]
JGit 配置选项

https://github.com/eclipse-jgit/jgit/blob/master/Documentation%2Fconfig-options.md

core.bigFileThreshold	50 MiB	✅	大于此大小的文件将以压缩方式存储，而不会尝试增量压缩。在不进行增量压缩的情况下存储大型文件可避免过多的内存使用，但略微会增加磁盘使用量。此外，大于此大小的文件始终被视为二进制。

core.packedGitLimit	10 MiB	✅	包文件中要在内存中缓存的最大字节数。


core.packedGitWindowSize	8 kiB	✅	在单个读取操作中加载到内存中的 pack 文件的字节数。这是 JGit 缓冲区缓存的 “页面大小”，用于所有 pack 访问操作。所有磁盘 IO 都以单个窗口读取的形式发生。将此值设置得太大可能会导致进程加载的数据多于所需数据;将此设置得太小可能会增加 read（） 系统调用的频率。

**Comment by Zacharia2** [comment]
```java
final WindowCacheConfig c = new WindowCacheConfig();
		c.setPackedGitLimit(128 * WindowCacheConfig.KB);
		c.setPackedGitWindowSize(8 * WindowCacheConfig.KB);
		c.setPackedGitMMAP(useMMAP);
		c.setDeltaBaseCacheLimit(8 * WindowCacheConfig.KB);
		c.install();```


安装此配置为实时设置。 * 
 * 新的配置将立即生效。如果新的限制小于当前已缓存的内容，那么较旧的条目将尽快被清除，以便缓存能够满足新的限制。

**Comment by Zacharia2** [comment]
https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/lib/Config.java#L794

https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/lib/ConfigConstants.java

应是根据这两个进行设置jgit的config。

https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.pgm/src/org/eclipse/jgit/pgm/Config.java


https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/util/SystemReader.java

**Comment by Zacharia2** [comment]
https://github.com/eclipse-jgit/jgit/blob/bb2bca135793a53779e5cdaf930fb3317e63f0aa/org.eclipse.jgit/src/org/eclipse/jgit/lib/InflaterCache.java#L52-L65


Don't end() user-supplied [Inf|Def]laters on closing stream

Calling close() on the following compression stream classes
*should not* invoke end() on the underlying Inflater/Deflater if it
was supplied in the stream class constructor:

    InflaterInputStream
    InflaterOutputStream
    DeflaterInputStream
    DeflaterOutputStream

This fix updates the behaviour of the close() method on those classes
to match the RI, allowing reuse of Inflater & Deflaters supplied to
stream class constructors.

This issue was initially observed using JGit on Android- JGit uses an
InflaterCache to recycle Inflaters, but in the cases where that Inflater
was used on a stream it would be returned to the cache in an invalidated
state. Seemingly-random exceptions would occur as the invalid Inflaters
were re-used in other contexts :-)

https://github.com/rtyley/agit/issues/47#issuecomment-3496045

Change-Id: Ia7b4b154820ba19ab08696978025c90b6fe2b1e5

**Comment by Zacharia2** [comment]
```java
        try {
            Os.setenv(Constants.GIT_CONFIG_NOSYSTEM_KEY,"111",true);
        } catch (ErrnoException ignore) {
        }
        String a = System.getenv(Constants.GIT_CONFIG_NOSYSTEM_KEY);
```

**Comment by Zacharia2** [comment]
```java
    public void setJgitConfig(){
        /*
         * "core", "bigFileThreshold", "50 MiB"  大于阈值的文件，将存储整个文件内容，而不是仅存储文件之间的差异
         * "core", "packedGitLimit", "10 MiB"  Git包文件存储在内存中的最大缓存大小
         * "core", "packedGitWindowSize", "8 kiB"  JGit 缓冲区 pack 访问操作缓存的 “页面大小”
         * "core", "packedGitOpenFiles ", "128"  一次可以打开的最大包文件数
         * "core", "deltaBaseCacheLimit ", "10 MiB"  用于存储 deltified 对象基底的缓存大小限制
         * "core", "dfs", "deltaBaseCacheLimit ", "10 MiB" 每个读取器 DFS 增量基本缓存中要保存的最大字节数。
         * "core", "dfs", "streamFileThreshold ", "50 MiB" 如果对象大小超过这个阈值，它将被流式传输
         */
//        UserConfigFile、FileBasedConfig、GIT_CONFIG_NOSYSTEM_KEY
//        mGit = Git.open(repoFile);
        final FS fs = mGit.getRepository().getFS();
        File configFile = fs.getGitSystemConfig();
        Timber.e(String.valueOf(configFile));

        if (configFile != null) {
            try {
                FileBasedConfig mConfig = new FileBasedConfig(null, configFile, fs);
                mConfig.load();
                mConfig.setString("core", null, "bigFileThreshold", "256 MiB");
                mConfig.setString("core", null, "packedGitLimit", "10 MiB");
                mConfig.setString("core", null, "packedGitWindowSize", "8 kiB");
                mConfig.setString("core", null, "packedGitOpenFiles ", "128");
                mConfig.setString("core", null, "deltaBaseCacheLimit ", "5 MiB");
                mConfig.setString("core", "dfs", "deltaBaseCacheLimit ", "5 MiB");
                mConfig.setString("core", "dfs", "streamFileThreshold ", "10 MiB");
                mConfig.save();
            } catch (IOException | ConfigInvalidException e) {
                Timber.e(e);
            }
        }
    }
```

把这个FS替换为我的，并重写userHome，不就可以了吗？

jgit.util.FS 可以 setUserHome

https://github.com/eclipse-jgit/jgit/blob/e1daefdd439859803ef99bbe843c99e405435f37/org.eclipse.jgit/src/org/eclipse/jgit/util/FS.java#L1192-L1195


```java
        final FS fs = FS.DETECTED.newInstance()
            .setUserHome(FsUtils.getAppDir(false))
            .setGitSystemConfig(new File(""));
        // /data/user/0/xyz.realms.mgit/files
        String userHome = String.valueOf(fs.userHome());
        File configFile = fs.getGitSystemConfig();
```

然后再一个阶段下就用这个FS。

https://github.com/eclipse-jgit/jgit/blob/e1daefdd439859803ef99bbe843c99e405435f37/org.eclipse.jgit.test/tst/org/eclipse/jgit/storage/file/FileBasedConfigTest.java#L214-L228


public static Git open(File dir, FS fs)

可以继承clonecommand，重写然后实现。

**Comment by Zacharia2** [comment]
将就用。

libgit需要绑定太难实现其JAVA唯一绑定模块不稳定，jgit在安卓上太不稳定但可以将就用。dart不知道，但有个笔记软件好像用的挺好。
